export const SET_USER = "SET_USER";
export const ADD_FAVORITES = "ADD_FAVORITES";
export const DELETE_FAVORITES = "DELETE_FAVORITES";
export const RATING_FAVORITES = "RATING_FAVORITES";
export const COMPLETED_FAVORITES = "COMPLETED_FAVORITES";